<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Readme_Generator</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        
        <Nullable>enable</Nullable><PackAsTool>true</PackAsTool>
        <ToolCommandName>readme</ToolCommandName>

        <PackageId>ReadmeGenerator</PackageId>
        <Version>1.0.4</Version>
        
        <UserSecretsId>44d166d9-d09c-4acc-89cc-b6c61225f3dc</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    </ItemGroup>

</Project>
